subject: Turniereinsatz nötig
opening: Hi ${current.firstName.value},
closing: Gruß,
signature: Ekkart.
filename:	${.now?date?string["yyyy-MM-dd"]}_Turniereinsatz_${current.fileName.value}.mmd

<#setting datetime_format="iso"><#setting locale="de">
Für den Erhalt der Lizenz ist es nötig, einmal im Jahr bei einem Turnier zu schiedsen.
Das hast Du laut unseren Unterlagen nicht getan.

Wir planen daher Deine Einsätze dieses Jahr in der zweiten Saisonhälfte, um Dir die Chance zu geben, bis Ende Januar bei einem Turnier zu schiedsen.
Solltest Du das nicht tun, werden wir Deine Einsätze anderweitig vergeben und Deine Lizenz auf passiv setzen.

Falls wir etwas übersehen haben oder wir einfach drüber reden sollen, melde Dich.
