subject:	Einteilung aktive Verbandsschiedsrichter
subtitle:	BTTV, Saison ${refdata.content.season.title.value}
date:			Stand: <#setting datetime_format="iso"><#setting locale="de"> ${refdata.info.modified?datetime?string["d. MMMM yyyy"]}
filename:	${refdata.content.season.title.value}_BeTTV_VSR-Einteilungsliste.mmd
options:	orientation=landscape

<!--

\footnotesize

\tabulinesep=_.5\parskip^.5\parskip

\begin{longtabu}[l]{@{}>{\RaggedRight}p{.15\textwidth}@{\hspace{.01\textwidth}}>{\RaggedRight}p{.18\textwidth}@{\hspace{.01\textwidth}}%
				>{\RaggedRight}p{.08\textwidth}@{\hspace{.01\textwidth}}>{\RaggedRight}p{.18\textwidth}@{\hspace{.01\textwidth}}>{\RaggedRight}p{.18\textwidth}@{\hspace{.01\textwidth}}>{\RaggedRight}p{.18\textwidth}@{}}
		\toprule
		\textbf{\scriptsize Name} & \textbf{\scriptsize Mitglied\newline\textsl{Schiedst für}} & \textbf{\scriptsize Ausb.\newline\textsl{VSR seit}} & \textbf{\scriptsize Adresse} & \textbf{\scriptsize Bevorzugt schiedsen} & \textbf{\scriptsize Nicht schiedsen}\\
		\midrule
	\endhead
		\midrule
		\multicolumn{6}{@{}r@{}}{\emph{\scriptsize weiter auf der nächsten Seite\dots}}\\
		\bottomrule
	\endfoot
		\bottomrule
	\endlastfoot

<#list selection as referee>
<#if referee?item_parity == "odd" >\rowcolor{Linen}<#else>\rowcolor{white}</#if>
--><#if referee.status.mmdmarkupstart??>${referee.status.mmdmarkupstart.value}</#if>${referee.tableName.value}<#if referee.status.mmdmarkupend??>${referee.status.mmdmarkupend.value}</#if><!-- &
--><#if referee.status.mmdmarkupstart??>${referee.status.mmdmarkupstart.value}</#if>${referee.member.displayText.value}<#if referee.status.mmdmarkupend??>${referee.status.mmdmarkupend.value}</#if><#if referee.reffor??><!--\newline\textsl{--><#if referee.status.mmdmarkupstart??>${referee.status.mmdmarkupstart.value}</#if>${referee.reffor.displayText.value}<#if referee.status.mmdmarkupend??>${referee.status.mmdmarkupend.value}</#if><!--}--></#if><!-- &
--><#if referee.status.mmdmarkupstart??>${referee.status.mmdmarkupstart.value}</#if>${referee.highestTrainingLevel.type.shorttitle.value}<#if referee.firstTrainingLevel?? && referee.firstTrainingLevel.since?? ><!--\newline\textsl{-->${referee.firstTrainingLevel.since.value?date['yyyy-MM-dd']?string['dd.MM.yyyy']}<!--}--></#if><#if referee.status.mmdmarkupend??>${referee.status.mmdmarkupend.value}</#if><!-- &
--><#if referee.primaryAddress??><#if referee.status.mmdmarkupstart??>${referee.status.mmdmarkupstart.value}</#if>${referee.primaryAddress.displayTitle.value}<#if referee.status.mmdmarkupend??>${referee.status.mmdmarkupend.value}</#if></#if><!-- &
--><#list referee.prefer as prefer><#if referee.status.mmdmarkupstart??>${referee.status.mmdmarkupstart.value}</#if>${prefer.displayText.value}<#if referee.status.mmdmarkupend??>${referee.status.mmdmarkupend.value}</#if><#sep><!--\newline --></#sep></#list><!-- &
--><#list referee.avoid as avoid><#if referee.status.mmdmarkupstart??>${referee.status.mmdmarkupstart.value}</#if>${avoid.displayText.value}<#if referee.status.mmdmarkupend??>${referee.status.mmdmarkupend.value}</#if><#sep><!--\newline --></#sep></#list><!--
\\
<#if referee.remark??>
<#if referee?item_parity == "odd" >\rowcolor{Linen}<#else>\rowcolor{white}</#if>
&\multicolumn{5}{@{}>{\RaggedRight}p{.37\textwidth}@{}}{--><#if referee.status.mmdmarkupstart??>${referee.status.mmdmarkupstart.value}</#if>*${referee.remark.value}*<#if referee.status.mmdmarkupend??>${referee.status.mmdmarkupend.value}</#if><!--}\\
</#if>
</#list>

\end{longtabu}


-->

**Legende:**

<#list refdata.content.statusType as statustype>
- <#if statustype.mmdmarkupstart??>${statustype.mmdmarkupstart.value}</#if><#if statustype.remark??>${statustype.remark.value}<#else>${statustype.title.value}</#if><#if statustype.mmdmarkupend??>${statustype.mmdmarkupend.value}</#if>
</#list>
